// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XMMULT_TOP_H
#define XMMULT_TOP_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xmmult_top_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Control_BaseAddress;
} XMmult_top_Config;
#endif

typedef struct {
    u32 Control_BaseAddress;
    u32 IsReady;
} XMmult_top;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XMmult_top_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XMmult_top_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XMmult_top_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XMmult_top_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XMmult_top_Initialize(XMmult_top *InstancePtr, u16 DeviceId);
XMmult_top_Config* XMmult_top_LookupConfig(u16 DeviceId);
int XMmult_top_CfgInitialize(XMmult_top *InstancePtr, XMmult_top_Config *ConfigPtr);
#else
int XMmult_top_Initialize(XMmult_top *InstancePtr, const char* InstanceName);
int XMmult_top_Release(XMmult_top *InstancePtr);
#endif

void XMmult_top_Start(XMmult_top *InstancePtr);
u32 XMmult_top_IsDone(XMmult_top *InstancePtr);
u32 XMmult_top_IsIdle(XMmult_top *InstancePtr);
u32 XMmult_top_IsReady(XMmult_top *InstancePtr);
void XMmult_top_EnableAutoRestart(XMmult_top *InstancePtr);
void XMmult_top_DisableAutoRestart(XMmult_top *InstancePtr);


void XMmult_top_InterruptGlobalEnable(XMmult_top *InstancePtr);
void XMmult_top_InterruptGlobalDisable(XMmult_top *InstancePtr);
void XMmult_top_InterruptEnable(XMmult_top *InstancePtr, u32 Mask);
void XMmult_top_InterruptDisable(XMmult_top *InstancePtr, u32 Mask);
void XMmult_top_InterruptClear(XMmult_top *InstancePtr, u32 Mask);
u32 XMmult_top_InterruptGetEnabled(XMmult_top *InstancePtr);
u32 XMmult_top_InterruptGetStatus(XMmult_top *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
