// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xmmult_top.h"

extern XMmult_top_Config XMmult_top_ConfigTable[];

XMmult_top_Config *XMmult_top_LookupConfig(u16 DeviceId) {
	XMmult_top_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XMMULT_TOP_NUM_INSTANCES; Index++) {
		if (XMmult_top_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XMmult_top_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XMmult_top_Initialize(XMmult_top *InstancePtr, u16 DeviceId) {
	XMmult_top_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XMmult_top_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XMmult_top_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

