# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2013.3
# Copyright (C) 2013 Xilinx Inc. All rights reserved.
# 
# ==============================================================

#
# Settings for Vivado implementation flow
#
set top_module mmult_top
set language verilog
set family zynq
set device xc7z045
set package ffg900
set speed -1
set clock ap_clk
set fsm_ext "auto"

# For customizing the implementation flow
set add_io_buffers false ;# true|false
set comb_luts false      ;# true|false
